### ISSUE TITLE
A question about r_TMS

### ISSUE THREAD

**Issue by chixiangxiang-lzt** [umair-hassan/best-toolbox#38]
In your presentation, you haven't shown the r_TMS in 'dependent' states, and we meet a problem with this. there is no response on GUI and some error on the command window of MatLab when we choose states 'dependent'. Does there have any other required thing when we choose the 'dependent' state?

**Comment by umair-hassan** [comment]
Dear Chixiangxiang,

Thanks for your interest. If you are interested in creating a brain-state dependent rTMS protocol, I would recommend to build an MEP measurement protocol in a brain-state dependent fashion and build the pulse sequence using pulse frequency input argument.  The rTMS protocol at the moment does not have any input, however this option is still there as a place holder for future and approved brain- state dependent rTMS protocols. 

If you still have any questions, feel free to ask.

Best, Umair

**Comment by chixiangxiang-lzt** [comment]
thank you very much!
| |
刘泽涛
|
|
***@***.***
|
签名由网易邮箱大师定制
On 5/9/2022 20:43，Umair ***@***.***> wrote：

Dear Chixiangxiang,

Thanks for your interest. If you are interested in creating a brain-state dependent rTMS protocol, I would recommend to build an MEP measurement protocol in a brain-state dependent fashion and build the pulse sequence using pulse frequency input argument. The rTMS protocol at the moment does not have any input, however this option is still there as a place holder for future and approved brain- state dependent rTMS protocols.

If you still have any questions, feel free to ask.

Best, Umair
