### ISSUE TITLE
Issue running in Matlab R2022a

### ISSUE THREAD

**Issue by JonteP** [umair-hassan/best-toolbox#40]
When executing the Toolbox with BEST I get the following output:

`ans = 

    HBox

Cannot define property 'Enable' in class 'uiextras.Panel' because the property has already been defined in the superclass
'matlab.ui.container.Panel'.

Error in best_application/create_hwcfg_panel (line 7827)
            uiextras.Panel( 'Parent', obj.hw.hbox, 'BorderType','none')

Error in best_application/create_gui (line 64)
            obj.create_hwcfg_panel;

Error in best_application (line 36)
            obj.create_gui;

Error in BEST (line 15)
    evalin( 'base', 'best_toolbox=best_application;' )`

After this, I get the following error if trying to close the GUI, and it refuses to close the window:

`Error while evaluating Figure CloseRequestFcn.`

**Comment by umair-hassan** [comment]
Hi Jonte, 

Thank you for contacting us. BEST toolbox is not compatible with Matlab r2022a. We are working on it. Matlab 2017b is the stable version validated for BEST toolbox releases. I hope this helps you. 

Thank you

**Comment by umair-hassan** [comment]
Do let me know if you need any help! Thanks
